apiVersion: v1
kind: Secret
metadata:
  name: lctmr-secret
  namespace: czl-test
type: Opaque
data:
  # Base64编码的密码和密钥
  DB_PASSWORD: RGRzbHIqMjAyNSNhYXA=
  JWT_SECRET: N1l0WUFNSlVhNExhcUNoYmtWMGlONUlNU0h2YUJDVnRCbVVrdFpYM0U4Sk9HMGkrNFRTaEg1dlhsMkhibGVVTU5JVGk0dGhGaVl2OFVGYmRpYXprcUE9PQ==